### ISSUE TITLE
TypeError: issubclass() arg 2 must be a class or tuple of classes

### ISSUE THREAD

**Issue by shaunbrady** [django-polymorphic/django-polymorphic#109]
Good day,
    I may be barking up the wrong tree, but I'm grasping at straws.  This may be an issue with django_polymorphic, but it could just as easily be "Sorry shaunbrady, your princess is in another castle".  With some new tests I have been writing, celery (https://github.com/RentMethod/django-celery-testworker/ to be specific) produces this error:

```
2014-10-27 10:31:48,679: WARNING/MainProcess] celery@excalibur ready.
[2014-10-27 10:32:53,698: ERROR/Worker-3] StartSessionTask for session ef5d6af8-eb1b-4f62-a7ca-a779119ebeb0 failed: issubclass() arg 2 mu
st be a class or tuple of classes
Traceback (most recent call last):
  File "/home/sbrady/.virtualenvs/site-awesim/src/session-epi/session_epi/tasks.py", line 52, in run
    session = EpiSession.objects.get(uuid=uuid)
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/polymorphic/query.py", line 280, in iterator
    real_results = self._get_real_instances(base_result_objects)
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/polymorphic/query.py", line 176, in _get_real_instances
    real_concrete_class = base_object.get_real_instance_class()
  File "/home/sbrady/.virtualenvs/site-awesim/local/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 116, in get_real_instance_class
    and not issubclass(model, self.__class__._meta.proxy_for_model):
TypeError: issubclass() arg 2 must be a class or tuple of classes
```
Possibly of interest, the tests work if I run one or two at a time, so a timing or cache issue makes sense.

Traveling to line 115 of polymorphic_model.py, I put some debugging in right before:
```
        if model is not None \
        and not issubclass(model, self.__class__) \
        and not issubclass(model, self.__class__._meta.proxy_for_model):
```
The code:
```
        print "model is {0}".format(model)
        print "self.__class__ is {0}".format(self.__class__)                                                  
        print "self.__class__._meta.proxy_for_model is {0}".format(self.__class__._meta.proxy_for_model)
```

Produces:
```
[2014-10-27 10:43:03,892: WARNING/Worker-4] model is <class 'session_epi.models.EpiApplicationConfiguration'>
[2014-10-27 10:43:03,892: WARNING/Worker-4] self.__class__ is <class 'session_epi.models.EpiSession'>
[2014-10-27 10:43:03,892: WARNING/Worker-4] self.__class__._meta.proxy_for_model is None
```

session_epi.models.EpiApplicationConfiguration is a model in the same app as EpiSession, but they do not inherit from each other.  They share a few mixins and are both model.Models, but are otherwise separate.  As well EpiApplicationConfiguration is not used any where near the calling code.

Adding 
```
ContentType.objects.clear_cache()
```
immediately above the line
```
model = ContentType.objects.get_for_id(self.polymorphic_ctype_id).model_class()
```
fixes the issue; all four tests complete just fine.  No debugging output is sent.  I believe this implies that AttributeError was raised and None was returned.  

From https://docs.djangoproject.com/en/1.6/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentTypeManager.clear_cache
it indicates one should not have to clear the cache.  I'm not sure if that applies to apps like django_polymorphic or to higher level applications.  Let me know if you think something else should be doing this work for us, if there is a better way to make sure this cache is clear, or if this only coincidentally fixes the issue.  

We are using Django 1.6.5 and django_polymorphic 0.5.6 from pip.  Upgrading to django_polymorphic 0.6 does not fix the issue.  

Thanks for any help.  I can provide you with any more information you want.  

SB

**Comment by kalouantonis** [comment]
+1

**Comment by kalouantonis** [comment]
In my case this turned out to be an app configuration error.

I was using `python manage.py loaddata app_name`, but the `polymorphic_ctype` foreign key was set to an invalid ContentType.

I hope this helps someone.

**Comment by aubricus** [comment]
This a bit late, but in the spirit of @kalouantonis comment, I wanted to share how I worked around this limitation in dumpdata.

Initial Steps (after getting this error):

1. Delete fixture record pointing to the polymorphic_ctype
2. Delete all fixture records pointing to the previous record
3. Reload fixtures
4. Re-enter the content I removed in the previous step
5. Re-dump fixtures (see below)

```
# The key option here is --natural-foreign
python manage.py dumpdata --natural-foreign --indent=4 -o ./fixtures/fixtures.json
```

[Here's the Django Docs on --natural-foreign](https://docs.djangoproject.com/en/dev/ref/django-admin/#cmdoption-dumpdata-natural-foreign)

They even mention to use this option when exporting `contenttypes`; but it's easy to miss.

Anyway, hope this helps someone!

**Comment by meiblorn** [comment]
I've faced with the same exception when I was trying to open admin page for sub-model. After about 1 hour of mindgames I figured out what is the root cause.

My migration was applied incorrectly: parent and sub-entities had same value for the "polymorphic_ctype" and, as result, type of all the sub-entities was recognized as type of parent. That happened  because of I copy-pasted migration from [here](https://django-polymorphic.readthedocs.io/en/stable/migrating.html#filling-the-content-type-value).

The solution is to change `forwards_func` source code to handle existing parent-child inheritance relationships as follows:
```python
from django.db import migrations, models
from django.db.models import Q

def forwards_func(apps, schema_editor):
    models = apps.get_app_config('mlpipelines').get_models()
    content_type = apps.get_model('contenttypes', 'ContentType')
    for model in models:
        new_ct = content_type.objects.get_for_model(model)
        objects = model.objects.filter(
            Q(polymorphic_ctype__isnull=True)
            | ~Q(polymorphic_ctype=new_ct))

        objects.update(polymorphic_ctype=new_ct)

class Migration(migrations.Migration):
    .... and etc.
```

My env:
```
Django==2.0.4
django-polymorphic==2.0.3
django-rest-polymorphic==0.1.7
```

**Comment by Eluzive** [comment]
I also ran into the same issue and noticed I had two children entities in different classes that were pointing to the same parent class. Ended up deleting the erroneous entity and now this exception isn't thrown when I try to run my unit tests.
