### ISSUE TITLE
Inheriting from PolymorphicModel and an abstract Model

### ISSUE THREAD

**Issue by lorinkoz** [django-polymorphic/django-polymorphic#128]
Django is complaining (in a warning) that the model is being registered twice. Any way to work this around?

**Comment by vdboor** [comment]
It's not needed to inherit from both, simply inherit from `PolymorphicModel`, which in itself inherits from `Model` already.

**Comment by lorinkoz** [comment]
It is needed, of course it is. Sometimes you want to split some functionality across multiple abstract Models, and you might just want to make one of those models inheriting also polymorphic.
Also, the best example comes when you want a custom user model which is also polymorphic, you need to inherit from AbstractBaseUser and PolymorphicModel. If you say that this is not needed, then how can I work around this issue?

**Comment by vdboor** [comment]
Oh I see. I'm sorry. I understood you were trying to do `class MyModel(models.Model, PolymorphicModel)`.

You can freely mix the model classes. Can you provide some example code of what you're trying to do? It seems like you may have an import path issue (hence the Django warning), because inheriting from multiple models is perfectly supported. In fact, that is being used by one of my other packages, which does a `class PolymorphicMPTTModel(MPTTModel, PolymorphicModel)` inheritance (see https://github.com/edoburu/django-polymorphic-tree/blob/master/polymorphic_tree/models.py#L66)

**Comment by lorinkoz** [comment]
Sorry for being vague with my initial statement.
I'm using Django 1.8 and Django-Polymorphic 0.7
Example of my model definitions:

```python
from django.contrib.auth.models import AbstractBaseUser
from polymorphic import PolymorphicModel

class BaseUser(AbstractBaseUser, PolymorphicModel):
    pass

class User(BaseUser):
    pass
```
I get warnings in `manage.py check` and `manage.py runserver`

```
RuntimeWarning: Model 'BaseUser' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
new_class._meta.apps.register_model(new_class._meta.app_label, new_class)

RuntimeWarning: Model 'User' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
```

I think the problem is with metaclasses registering the model on their own every time (twice in this case, thrice if I add another model inheriting from `BaseUser`, and so forth). Perhaps I'm not following the right path to inherit from both. Any clue?

**Comment by bbirand** [comment]
Should this issue be re-opened? I would also be interested in the result..

**Comment by lorinkoz** [comment]
Hi, vdboor. Is this a won't fix? Can we re-open it or see variants to work it around?

**Comment by vdboor** [comment]
Nope, good that you ping again.
One of the things I wonder is, would it matter if you switch the inheritance order, have `PolymorphicModel` first? Also, if you just inherit from `PolymorphicModel` as experiment, would that work or still raise the warnings?

**Comment by lorinkoz** [comment]
If I inherit from `PolymorphicModel` alone it works fine. Switching the order has no effect.The problem is with multiple ascendants registering the model.
I would love to see this working all good with a custom user model, to take advantage of the polymorphic behaviour and have `request.user` pointing to the correct subclass.
I frankly don't know why Django core is launching the warning for registering a model multiple times, perhaps they think it might break things in the future. Truth is everything works fine except for the annoying warning.

**Comment by pmuller** [comment]
Same issue. Any update ?

**Comment by thenewguy** [comment]
I've observed this as well in dj 1.10 and current 1.0.1 polymorphic

**Comment by byoungb** [comment]
I have the same issue. dj 1.9.9 and current 1.0.1 polymorphic.

```python
class BaseProduct(PolymorphicModel):
    ...
    class Meta:
        db_table = 'product'
        abstract = True

class BaseSubProduct(models.Model):
    ...
    class Meta:
        db_table = 'sub_product'
        abstract = True

class Product(BaseProduct):
    pass

class SubProduct(BaseSubProduct, Product):
    pass
```
I know this seems overly complicated, but it works just fine until I changed BaseProduct from models.Model to PolymorphicModel.

Well actually it still works fine it just throws that error message.

And switching the order in my case does stop the error but then the wrong meta is loaded with the wrong table.

**Comment by lorinkoz** [comment]
Looks like this is working good with Django 1.10 and Polymorphic 1.1 AS LONG AS the polymorphic base is the first inherited class. It's now working for me even with polymorphic User classes.

If you had the same issue, please confirm whether it's working or not in order to close the issue.

**Comment by lorinkoz** [comment]
Closing then

**Comment by DylannCordel** [comment]
Django 1.11 + django-polymorphic 2.0.3
@lorinkoz Sorry to comment on this old issue but it seems there is a problem when Polymorphic base is the first inherited class : it breaks the MRO. For eg:

```python

class DocumentBase(PolymorphicModel):

    class Meta:
        abstract = True

    def toto(self):
        print 'toto from DocumentBase'

class PackageDocumentBase(models.Model):
    
    class Meta:
        abstract = True

    def toto(self):
        print 'toto from PackageDocumentBase'
        super(PackageDocumentBase, self).toto()


class Document(DocumentBase):
    pass


class PackageDocument(Document, PackageDocumentBase):
    pass


package_document = PackageDocument()
package_document.toto()
# prints : "toto from DocumentBase" only
```

`package_document.toto()` will execute `DocumentBase.toto` only (and not `DocumentBase.toto` then `DocumentBase.toto` via super)

To solve this, we created a mixin which holds overwritable methods. Above code becomes:


```python

class PolymorphicDocumentMixin(object):

    def toto(self):
        print 'toto from PolymorphicDocumentMixin'


class DocumentBase(PolymorphicModel):

    class Meta:
        abstract = True

    #  no more toto method here


class PackageDocumentBase(PolymorphicDocumentMixin, models.Model):
    
    class Meta:
        abstract = True

    def toto(self):
        print 'toto from PackageDocumentBase'
        super(PackageDocumentBase, self).toto()


class Document(DocumentBase):
    pass


class PackageDocument(Document, PackageDocumentBase):
    pass


package_document = PackageDocument()
# prints : "toto from PackageDocumentBase"
# prints : "toto from DocumentBase"
```

With this work-around, children can overrides methods from the mixin (and call the original one via super). It would be great if django-polymorphic could manage this problem but at least, there is a solution to do what we want :)

**Comment by lorinkoz** [comment]
Thanks @DylannCordel . This doesn't break for me because I am using a simpler scheme for "overriding" methods, but your certainly make a case. The choice would be assuming in the parent (direct descendant from `PolymorphicModel`) that they would be first in MRO, and therefore calling `super` there as well (or doing some sort of dark magic check on whether to call `super` or not,) which anyways breaks the natural feeling of inheritance and polymorphism. Hope your fix is useful for anyone with the same problem.
