### ISSUE TITLE
Field type incorrect in child class vs parent class

### ISSUE THREAD

**Issue by earthfront** [django-polymorphic/django-polymorphic#224]
Sorry, don't have time to submit _exact_ reproduction steps.

**Environment:**
I have an abstract class with a JSONField:
class A:
    json = JSONField()
    class Meta:
       abstract = True

A polymorphic base class, and a child class:
class Doc(Polymorphic..., A):
    ....
class ChildDoc(Doc):
   ....

**Expected behavior:**
Get an instance of ChildDoc, use json member as a JSONField.

**Actual behavior:**
When I get the child class, the type of "json" is unicode object. Accessed via the embedded parent_ptr, it's the correct (ish) type.

``` python
In [52]: a = Doc.objects.all().first()
In [53]: a?
Type:           ChildDoc
In [54]: a.json?
Type:        unicode
In [55]: a.doc_ptr.json?
Type:        dict
```

The documentation doesn't mention any caveats like this.

**Comment by earthfront** [comment]
Versions:
Django==1.9.6
polymorphic==0.9.2

**Comment by hornn** [comment]
This issue is reproduced with Django==1.8.15 and django-polymorphic==1.0.2.
Is it fixed in a later version?
