### ISSUE TITLE
TypeError: 'PolymorphicModelBase' object is not iterable

### ISSUE THREAD

**Issue by mekhami** [django-polymorphic/django-polymorphic#227]
http://dpaste.com/2Z3RH41

`TypeError: 'PolymorphicModelBase' object is not iterable`

I am getting this error when trying to set up the admin for my polymorphic models. Here's a link to the admin for those models: https://gist.github.com/mekhami/07288765ad1b6d72ed4bda10022a0581

And here's a link to the models themselves: https://gist.github.com/mekhami/c27333c7c217e1da07f618f8a29ed517

Any insight? I think I've followed the documentation to a letter..

**Comment by mekhami** [comment]
Ah, so the documentation is a bit outdated. child_models should be an iterable of (Model, ModelAdmin) tuples.

So there's a documentation fix to be made here anyway.

**Comment by glifchits** [comment]
Bump: the docs should get updated!
