### ISSUE TITLE
PIP update

### ISSUE THREAD

**Issue by BenDevelopment** [django-polymorphic/django-polymorphic#248]
When will be the PIP installer updated with the last version? I need it to deploy my application :-).

**Comment by vdboor** [comment]
Use `pip install -U pip` - this has little to do with polymorphic.

**Comment by BenDevelopment** [comment]
That is not what I mean. When I install django-polymorphic with PIP, the downloaded version is not the same as this depo. For exemple, the folder contrib is not included in the downloaded version with pip install. I have to download manyally the sources from this depo and copy them in my site-package folder. I have to do that every time I deploy a new installation of my application.

**Comment by vdboor** [comment]
Ah, I see. I've uploaded a new release to PyPI.

FYI, when a project didn't release the latest commits yet, you can install a GitHub link via pip/requirements.txt too. (`pip install -e git+https://.../reponamegit@commitid`)

**Comment by BenDevelopment** [comment]
Thank you! I didn't know about the GitHub link in requirements.txt. Very good to know!
