### ISSUE TITLE
PolymorphicChildModelAdmin does not fix breadcrumbs

### ISSUE THREAD

**Issue by randomshinichi** [django-polymorphic/django-polymorphic#253]
I have a list display of Transactions, so far so good.
![1](https://cloud.githubusercontent.com/assets/9956122/20451228/6081a2b6-adf7-11e6-980b-18cb84251288.png)

However once I click on a particular Transaction, the breadcrumb becomes the child model, and there's no way to go back to the Transaction list display - only the TransactionNordea list display.
![2](https://cloud.githubusercontent.com/assets/9956122/20451252/8a8ed844-adf7-11e6-8d7d-f7cc788492e3.png)

This is my code so far, did I do everything right? Should I use inlines after all?
```
@admin.register(models.Transaction)
class TransactionParentAdmin(PolymorphicParentModelAdmin):
    base_model = models.Transaction
    child_models = [models.TransactionNordea]
    base_list_display = ("id", "payer", "amount_received", "client")


class TransactionChildAdmin(PolymorphicChildModelAdmin):
    base_model = models.Transaction


@admin.register(models.TransactionNordea)
class TransactionNordeaAdmin(TransactionChildAdmin):
    base_model = models.TransactionNordea

```

**Comment by nshafer** [comment]
I am also seeing this issue, and it's not huge, but it would be a good quality-of-life fix if ever possible.

**Comment by meshy** [comment]
Aha! I've worked it out! I had this issue too, but it's a mistake, not a bug!

With the example above, the `base_model` should not be changed on `TransactionChildAdmin`.

```python
@admin.register(models.TransactionNordea)
class TransactionNordeaAdmin(TransactionChildAdmin):
    pass
```

We were previously changing the `base_model` to be the _child_ model. This is incorrect!

**Comment by nshafer** [comment]
That also fixed it for me. I had incorrectly set `base_model` to the child's model, not the parent's. Thanks!
