### ISSUE TITLE
How to get base class?

### ISSUE THREAD

**Issue by Kurdakov** [django-polymorphic/django-polymorphic#260]
Sorry for just a basic question - but I searched and did not find answer.

I have something like:
```
class Project(PolymorphicModel):
   topic = models.CharField(max_length=30)

class ArtProject(Project):
    artist = models.CharField(max_length=30)

class ResearchProject(Project):
    supervisor =  models.CharField(max_length=30)
```

now I create ArtProject or ResearchProject  via gui, but later in I need to access objects via another gui which lists only base object types. So while I create ArtProject I need to know  base  object type to associate base type and concrete object, but there is no way to obtain it 
because
ContentType.objects.get_for_id(object.polymorphic_ctype_id) gives me current type, 
but I need base type and there is no something like base_ctype_id

so how to get base type ( class Project(PolymorphicModel) ) from  derived object of class ArtProject or class ResearchProject?

**Comment by Kurdakov** [comment]
a solution was
```
content_type = ContentType.objects.get_for_model(derivedobject._meta.parents.keys()[-1])
```
still it will be convenient to have a method to access base types built into library

**Comment by vivazzi** [comment]
@Kurdakov You can use derivedobject._materialized_model

**Comment by vdboor** [comment]
You can use `polymorphic.utils.get_base_polymorphic_model()`
