### ISSUE TITLE
Preferred method to create an object with a PolymorphicModel field through code?

### ISSUE THREAD

**Issue by mdhari** [django-polymorphic/django-polymorphic#281]
I have my models setup like this:
```
class Response(PolymorphicModel):
    pass

class RadioResponse(Response):
    pass

class LongTextResponse(Response):
    pass

class Question(models.Model):
    response_type = models.ForeignKey(Response, related_name="+")
```
What's the preferred way to create an object with a PolymorphicModel. I thought this would work:
```
Question.objects.get_or_create(
    response_type = LongTextResponse.objects.create(),
)
```
But I'm getting a `ContentType matching query does not exist.` in the admin panel.

When I use the Parent/Child Admin panel, I'm able to create it easily. But I need to do this through code.

**Comment by vdboor** [comment]
Your code seems correct, I wonder whether the database was already initialized?
