### ISSUE TITLE
Querying by model type specifing query doesn't work

### ISSUE THREAD

**Issue by faxioman** [django-polymorphic/django-polymorphic#286]
Hi.
I'm trying a query like:

```
my_polymorphic_qs.filter(myapplabel__MyModel___myfield='something')
```
but I get this error:

```
module 'django.db.models' has no attribute 'get_model'
```

I see in query_translate.py/translate_polymorphic_field_path method that you are using models.get_model ... maybe is not working in recent django versions?

**Comment by vdboor** [comment]
Thanks, I've fixed this issue, and it will be part of the next release.
