### ISSUE TITLE
Proxies in django polymorphic

### ISSUE THREAD

**Issue by Kurdakov** [django-polymorphic/django-polymorphic#308]
Proxies in Django  are usually used for separating admin interface for some subsets of objects

let's take django-polymorphic pexp example 
I'd like to have Projects to be grouped in separate admin, so, additionally to pexp example define

in models.py
```
class ProjectProxy(Project):
    class Meta:
        proxy = True
```
in admin.py
```
class ProjectProxyAdmin(admin.ModelAdmin):
    model = ProjectProxy
admin.site.register(ProjectProxy, ProjectProxyAdmin)
```
after creating
ProxyProject objects are safe in separate admin,
ProxyProject objects are also listed in Project admin,
but when they are clicked - there is 403 Forbidden message.

now it is possible to add ProxyProject  to
```
class ProjectAdmin(PolymorphicParentModelAdmin):
    base_model = Project
    list_filter = (PolymorphicChildModelFilter,)
    child_models = (Project, ArtProject, ResearchProject,ProjectProxy)
```
but then - ProjectProxy is listed in admin/pexp/project/add/ types,  but is absolutely not needed here - if I want to have new Project objects - it does not mean I want to clutter the admin interface with spurious proxy objects

so is it possible to have either

1) not raise forbidden for objects in Projects at /admin/pexp/project/ ( if model is not listed as child_models,but for proxy it's base is in child models)
2) ability to explicitly exclude models registered child_models from a list of available models in admin/pexp/project/add/

the second option can be achieved by  having PolymorphicParentModelAdmin field skipProxies
and then in def get_child_type_choices(self, request, action):
have
```
if skipProxies and model._meta.proxy == True:
                continue
```
P.S. in above illustrative example it makes no sense to have all Projects in both Proxy admin and in normal polymorphic admin, but it really makes sense if a desire is  to place all ArtProject objects in a separate admin:
```
class ArtProjectProxy(ArtProject):
    class Meta:
        proxy = True

class ArtProjectProxyAdmin(admin.ModelAdmin):
    model = ArtProjectProxy
    def get_queryset(self, request):
        return ArtProject.objects.all()
```
still - it will cause above mentioned problems ( 403 error or list of additional ArtProjectProxy in polymorphic admin )

**Comment by vdboor** [comment]
No, sorry you can't and shouldn't do that.

When you store the model as a proxy, this information is retained, so upon retrieval polymorphic would return the proxy model as well. That is why the add dialog is consistent with it.
