### ISSUE TITLE
Create Release v1.3

### ISSUE THREAD

**Issue by jstarcher** [django-polymorphic/django-polymorphic#309]
Can you please consider creating a release so that the djstripe project can officially pickup some changes sitting in master? The project is blocked on their release from this specifically.

Thanks!

**Comment by meshy** [comment]
Looks as though this has now been released! \o/

https://pypi.python.org/pypi/django_polymorphic/1.3

**Comment by vdboor** [comment]
done, thanks for the reminder in both threads!
