### ISSUE TITLE
RegexURLResolver usage

### ISSUE THREAD

**Issue by jleclanche** [django-polymorphic/django-polymorphic#314]
RegexURLResolver has been renamed in Django 2.1, this is causing failures on Travis.

One of the django devs noted that it's a private API and we could use url() instead.

**Comment by meshy** [comment]
I've addressed the rename in https://github.com/django-polymorphic/django-polymorphic/pull/318 (which is not yet ready to merge).

You've mentioned another way here -- if you know the details, could you please comment on the PR with your suggestion?

Many thanks.
