### ISSUE TITLE
[Question] Declare polymorphic on custom field.

### ISSUE THREAD

**Issue by lsnk** [django-polymorphic/django-polymorphic#317]
Hello. I want to make a code similar to SQLAlchemy one like this. I've read the documentation but haven't found such thing. Is this possible in django-polymorphic?

```
class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    type = Column(String(20))

    __mapper_args__ = {
        'polymorphic_on':type,
        'polymorphic_identity':'employee'
    }

class Manager(Employee):
    manager_data = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'manager'
    }

class Engineer(Employee):
    engineer_info = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'engineer'
    }
```

**Comment by vdboor** [comment]
The polymorphic and Django API's work slightly different and a bit more high-level. by inheriting from `PolymorphicModel` you get all functionality in your model. It installs it's own `polymorphic_ctype` field that is used, so no `polymorphic_on` or `polymorphic_identity` fields are needed.

When you create a `ForeignKey` to a polymorphic model, it will give you polymorphic behavior by default. You can use `.non_polymorphic()` on the queryset to disable that. For example: `mymodel.related_field.non_polymorphic()`
