### ISSUE TITLE
Python 2.7 + Django 1.11 breaking

### ISSUE THREAD

**Issue by tony** [django-polymorphic/django-polymorphic#332]
This is blocking CI #331

Found while QA'ing #318: https://github.com/django-polymorphic/django-polymorphic/pull/318#issuecomment-349707486

9500a21f82dd1b31f88d88e46bf8aa2411a701e9 works

break starts here: 80b4f2bb41423d6131e2e39ef5c6b212ce5a7b56

**Comment by tony** [comment]
I notice that ``repr`` comparisons (that'd check against id) were taken out here: https://github.com/django-polymorphic/django-polymorphic/commit/80b4f2bb41423d6131e2e39ef5c6b212ce5a7b56#diff-6abafedbc794844c3d3bf058ba4f651cL32

This leads me to believe that assertions against the id of an object may not be essential. Though, I can't find any larger PR that goes into the thought process behind it.

I don't think we have the same option of testing against models themselves, we need assert the field in question is deferred.

So we may be able to rewrite the defer tests to test against a regex where the id can be any number.

**Comment by meshy** [comment]
Django's own tests check this by looking at the queries that are done to access the fields on the object. Perhaps that will be appropriate here too. Ref: https://github.com/django/django/blob/d7b9aaa366dd54ecc3142c588162e3adc7c2f7ac/tests/defer_regress/tests.py#L25-L36

**Comment by meshy** [comment]
I ended up using a regex check, as you proposed. It appears to have got the tests running on #318 `\o/`

**Comment by vdboor** [comment]
Fixed!
