### ISSUE TITLE
ForeignKey returns parent model instead of child

### ISSUE THREAD

**Issue by mumumumu** [django-polymorphic/django-polymorphic#341]
I'm in the process of upgrading from 1.3 to 2.0.2 and noticed something strange -- ForeignKeys to polymorphic models are returning the parent model instead of the child. 

Example scenario:
```
 class FKTest(models.Model):
     party = models.ForeignKey('parties.Party', related_name='fk_party')
     person = models.ForeignKey('parties.Person', related_name='fk_person')

party = person = Person.objects.first()
fktest = FKTest(party=party, person=person)
fktest.save()

# things look good before re-fetching from db
fktest.party
>> <Person:  Person object>
fktest.person
>> <Person:  Person object>

# after re-fetching from db
fktest = FKTest.objects.get(pk=fktest.pk)
fktest.party
>> <Party: Party object>
fktest.person
>> <Person:  Person object>
```

I'm on Django 1.11.10. It might turn out to be something specific to my code (and I'll continue debugging), buy any help would be appreciated.

**Comment by mumumumu** [comment]
I think I've figured out my issue. The attribute `PolymorphicManager.use_for_related_fields` has been deprecated in Django 2.0, but on 1.11 the [descriptors are still using that field](https://github.com/django/django/blob/1.11.10/django/db/models/fields/related_descriptors.py#L112-L119) to determine whether to use the polymorphic or base manager.

As a workaround I've monkey patched `use_for_related_fields` onto the `PolymorphicManager` in our base `AppConfig.ready` check.

**Comment by vdboor** [comment]
Ah yes, the `use_for_related_fields` was deprecated as of Django 1.10, and got replaced with setting `base_manager_name`.

As of Django 2.0, all managers are inherited, which is why we set `Meta.manager_inheritance_from_future` now - and thereby remove the need for overriding `base_manager_name` everywhere.
