### ISSUE TITLE
OneToOne `_ptr` fields to base model should set editable=False

### ISSUE THREAD

**Issue by AlanCoding** [django-polymorphic/django-polymorphic#349]
I believe you can see this behavior in the models from tests, such as:

https://github.com/django-polymorphic/django-polymorphic/blob/7fe7861f45ce42c4ced014d8f58c5c5f8603d203/polymorphic/tests/migrations/0001_initial.py#L880-L891

The field kwargs are

```
auto_created=True,
on_delete=django.db.models.deletion.CASCADE,
parent_link=True,
primary_key=True,
serialize=False,
to='tests.Middle'
```

I believe that when the field is created, the `editable` field is not provided, leaving it to default to `True`.

I have observed this in [AWX](https://github.com/ansible/awx) (a Django/DRF app that uses django-polymorphic) models as such:

```python
In [6]: JobTemplate._meta.get_field('unifiedjobtemplate_ptr').editable
Out[6]: True
```

Here, `JobTemplate` is a subclass of the polymorphic base model `UnifiedJobTemplate`, and `JobTemplate.unifiedjobtemplate_ptr` is the automatically-created reference from the subclass table to the base class table.

I think it would be pretty widely agreed that this field should not be editable? This could probably be accomplished by simply adding that kwarg wherever the field is generated.

**Comment by vdboor** [comment]
The `.._ptr`  field is a feature from Django. Django already hides primary keys (and likely `parent_link=True`) in a form.
