### ISSUE TITLE
Question about filter

### ISSUE THREAD

**Issue by csarcom** [django-polymorphic/django-polymorphic#354]
I could not find out in the docs.
I have:

```
class Supply(PolymorphicModel):
    pass

class Water(Supply):
    pass

class Beer(Supply):
    pass

class Soda(Supply):
    pass

class Consumption():
    supply = Supply()
```

I can create Consumptions with Water, Beer or Soda, but how  can I filter it?
Something like this:
`Consumption.objects.filter(supply__in=[Beer, Water])`

**Comment by csarcom** [comment]
I could filter doing this:

```
ctypes = ContentType.objects.filter(model__in=['water', 'beer'])
Consumption.objects.filter(supply__polymorphic_ctype__in=ctypes)
```

But probably its not the best way

**Comment by leewesleyv** [comment]
I think you are looking for the instance_of() filter. Check http://django-polymorphic.readthedocs.io/en/stable/quickstart.html.

For your example you can say Supply.instance_of(Beer, Water)
