### ISSUE TITLE
Django 2.1 raises exception in admin

### ISSUE THREAD

**Issue by mikedingjan** [django-polymorphic/django-polymorphic#360]
As of Django 2.1 Django started to raise an exception when a form has the ``empty_permitted`` and ``use_required_attribute``. In the admin of django-polymorpic these attributes are used together, which makes it impossible to use the Django admin interface

Related Django ticket: https://code.djangoproject.com/ticket/28171?cversion=1&cnum_hist=3

**Comment by vdboor** [comment]
FIxed and released 2.0.3!
