### ISSUE TITLE
Migrating polymorphic models to new app causes queryset to be empty

### ISSUE THREAD

**Issue by filipweidemann** [django-polymorphic/django-polymorphic#368]
I am currently in the middle of refactoring an old Django monolith into small and reusable apps. Some of those old models are inheriting from a polymorphic parent called `Asset`. 

Since the app is already running in production, I wanted to use the `db_table` Meta attribute when moving the individual models to the new app's `models.py`, so that they keep using their old table and therefore won't need new ones with data migrations or other fun like this.

This works perfectly when those moved models inherit from Django's `models.Model`, however those which are polymorhic seem to produce strange issues. 
Whenever you query one of those models, the returned `PolymorphicQueryset` is empty, even though the table is populated exactly as it was before. 

It gets stranger. When querying the `Asset` model directly, you would expect the children objects to show up. They don't. Even `Asset.objects.all()` doesn't return them. 

Is this some kind of bug, unexpected behaviour or maybe my own fault for implementing it incorrectly?

**Comment by filipweidemann** [comment]
EDIT: 

It seems like this is somehow related to the app the model lives in. When moving them out of their old app into a new one, but setting their `app_label` to the old app's name, it is working. However, this is not a workaround I want to be using, so an explanation what the issue here is would be extremely helpful.

**Comment by User3759685** [comment]
Could this have something to do with the content types? Just a guess, but I'd check those through.

**Comment by DavidVentura** [comment]
I am having the same issue. I verified that when creating a new instance of the model in the new app the ctype is different in the database

**Comment by filipweidemann** [comment]
Thank you @DavidVentura - I was observing the same, sorry for not noting this inside this ticket! This should provide enough evidence for people having the same issue, so I'll close this one.
