### ISSUE TITLE
'empty_form' is not used in polymorphic formsets, use 'empty_forms' instead.

### ISSUE THREAD

**Issue by gradywoodruff** [django-polymorphic/django-polymorphic#372]
Hi, I almost have my polymorphic inlines set up, but am running into an error:
`'empty_form' is not used in polymorphic formsets, use 'empty_forms' instead.`

I have looked through the docs and files, and related questions and was unable to find anything. Here is my set up. I'd appreciate any advice
```
class ContentInline(StackedPolymorphicInline):
    class TextContentInline(StackedPolymorphicInline.Child):
        model = Text
        fieldsets = [(None, {
                'fields': (('body',)),
            })]

    child_inlines = (TextContentInline,)
    model = Content
    extra = 1
    min_num = 1
    fieldsets = [(None, {
            'fields': (('post',)),
        })]

class PostAdmin(admin.ModelAdmin, PolymorphicInlineSupportMixin):
    save_on_top = True
    list_display = ['title', 'author', get_post_url, 'created']
    readonly_fields = [get_post_url, 'created',]

@admin.register(Article)
class ArticleAdmin(PostAdmin):
    inlines = [CoverPictureInline, ContentInline, ContextInline]
    fieldsets_and_inlines_order = ('f', 'i', 'i', 'f', 'i')
    fieldsets = tuple(primary_sets
        + [('Text', {
            'fields': (('body',),),
        })]
        + meta_sets)
```

**Comment by gradywoodruff** [comment]
I have it working now, and im not sure what it was that made it work. If i find the answer I will comment here just in case anyone runs into this in the future. Thanks for the amazing work on this package

**Comment by krsteve** [comment]
In case anybody's still running into this issue, maybe try inheriting **PolymorphicInlineSupportMixin** first. 

I.e.,

**DO**
class SomeAdmin(PolymorphicInlineSupportMixin, admin.ModelAdmin):
....

**DON'T**
class SomeAdmin(admin.ModelAdmin, PolymorphicInlineSupportMixin):
....
