### ISSUE TITLE
Filter by exact Model, not is_instance

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [django-polymorphic/django-polymorphic#377]
Is there a way to filter objects by exact Model?

i.e. if C inherits from B and B from A, 

```python
A.objects.instance_of(B)
```
will return all instances of B and C. How can I only get the instances of B?

Is

```python
B_content_type = ContentType.objects.get_for_model(B)
b = A.objects.filter( Q(polymorphic_ctype=B_content_type))
```

the only way?

**Comment by vdboor** [comment]
Yes, your example is correct! This is the only way currently to make such query.
