### ISSUE TITLE
Does `polymorphic` have to come before `django.contrib.contenttypes` in `INSTALLED_APPS`?

### ISSUE THREAD

**Issue by ksze** [django-polymorphic/django-polymorphic#384]
The documentation shows `polymorphic` comes before `django.contrib.contenttypes` in `INSTALLED_APPS`: https://github.com/django-polymorphic/django-polymorphic/blame/388d0e12c04f29578e4492ddb3507b1b7eee8431/docs/quickstart.rst#L10-L13

Does it _have_ to be this way? It's a little ugly to have to disturb the default ordering of Django's built-in apps.

**Comment by vdboor** [comment]
You can change the ordering to your liking, in this case, there is no need for a specific order!

one reason for other apps to require an ordering, is because they may override templates from the apps placed below them in `INSTALLED_APPS`
