### ISSUE TITLE
ManyToMany inline get_real_instance_class AttributeError when using `through` for InlineModel

### ISSUE THREAD

**Issue by SamStudio8** [django-polymorphic/django-polymorphic#385]
django seems to return a `ModelBase`-like object when using [`through`](https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.ManyToManyField.through), which causes `django-polymorphic` to raise an `AttributeError` when trying to create a `StackedPolymorphicInline`.

**Comment by SamStudio8** [comment]
I think this seems to be because Django doesn't know to return a `polymorphic.base.PolymorphicModelBase` when the polymorphic model is accessed via a `through`? I think I'll just redesign to avoid M2M as its somewhat messy for my use-case anyway.

**Comment by adamwojt** [comment]
Any solutions here for time being?

**Comment by araggohnxd** [comment]
Can't this be reopened? Same issue here.
