### ISSUE TITLE
IntegrityError (foreign key constraint violation) during unit test session

### ISSUE THREAD

**Issue by alex-oleshkevich** [django-polymorphic/django-polymorphic#402]
I have a very base setup:

`class Model`, `class ModelB(Model)`.

This works well in WSGI scope but fails when I run `manage.py test`.
The error is:
`django.db.utils.IntegrityError: insert or update on table "competitions" violates foreign key constraint "competitions_polymorphic_ctype_id_ea8f29c9_fk_django_co"
DETAIL:  Key (polymorphic_ctype_id)=(54) is not present in table "django_content_type".`

Versions:
Django 2.2.4
django-polymorphic 2.1.2

What may cause this issue?

---- FULL OUTPUT ---
```======================================================================
ERROR: test_update_active_revision (competitions.tests.test_views.UpdateActiveRevisionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "competitions" violates foreign key constraint "competitions_polymorphic_ctype_id_ea8f29c9_fk_django_co"
DETAIL:  Key (polymorphic_ctype_id)=(54) is not present in table "django_content_type".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 396, in execute
    return real_execute(self, sql, params)
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/.cache/pypoetry/virtualenvs/dealflow-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "competitions" violates foreign key constraint "competitions_polymorphic_ctype_id_ea8f29c9_fk_django_co"
DETAIL:  Key (polymorphic_ctype_id)=(54) is not present in table "django_content_type".
```

**Comment by alex-oleshkevich** [comment]
This happens when I have a custom Manager which overrides `get_queryset` like that:

```python    
from .models import ModelB
def get_queryset(self):
    return super().get_queryset().not_instance_of(ModelB)
````

**Comment by Eboreg** [comment]
I had a similar issue. In my case, it was due to ContentTypeManager's cache being populated with the wrong values. Maybe this is the case for you also? My issue here: https://github.com/django-polymorphic/django-polymorphic/issues/470

**Comment by voovoo** [comment]
Yes, I have the same problem during the Django test execution (the main app seems to work fine).

**Comment by andrewmende** [comment]
I had the same issue with content types and unit test, the following in test.py helped:

`from django.contrib.contenttypes.models import ContentType`

And put this in the beginning of the first test case:
`ContentType.objects.clear_cache()`

**Comment by Ruslan-Skira** [comment]
@alex-oleshkevich did you fix your problem. I'm stuck on it too.

**Comment by andrewmende** [comment]
> @alex-oleshkevich did you fix your problem. I'm stuck on it too.

Did you try the solution with `ContentType.objects.clear_cache()` ?

**Comment by Ruslan-Skira** [comment]
> > @alex-oleshkevich did you fix your problem. I'm stuck on it too.
> 
> Did you try the solution with `ContentType.objects.clear_cache()` ?

yep

**Comment by alex-oleshkevich** [comment]
> > @alex-oleshkevich did you fix your problem. I'm stuck on it too.
> 
> Did you try the solution with `ContentType.objects.clear_cache()` ?

I don't the lib anymore. I use JSON field with custom properties on the model.

**Comment by Safrone** [comment]
In case I come up on this again myself: I had this issue caused by storing and loading fixtures with django's built in serialization. I ended up having to do `ContentType.objects.for_model` and set the polymorphic_ctype explicitly before it deserialized since the saved fixtures' ctypes didn't line up with my test database

**Comment by s-nikhil-lilly** [comment]
@Safrone Hi i am also facing the same issue with the fixture. Can you explain me ur solution with example will be helpful to solve

**Comment by Safrone** [comment]
@s-nikhil-lilly 

this is basically what I used where `EntitySchedule` is my base polymorphic class

```python
...
for model in fixtures:
  meta = model._meta
  if issubclass(meta.model, EntitySchedule):
    ContentType.objects.clear_cache()
    ctype = ContentType.objects.get_for_model(meta.model)
    model.polymorphic_ctype = ctype
    if hasattr(model, 'entityschedule_ptr_id'):
      model.schedule_id = model.entityschedule_ptr.schedule_id
  model.save()
```

**Comment by s-nikhil-lilly** [comment]
@Safrone 
class TestResults(APITestCase):
    """Test POST and GET results"""
    fixtures = ["main_model/fixtures/a.yaml", "result/fixtures/b.yaml"]
    def setUp(self):
        ..............

I am using this method to run fixtures but it is getting failed
