### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by AndreyMZ** [django-polymorphic/django-polymorphic#443]
Django 3.0 was [released](https://docs.djangoproject.com/en/3.0/releases/3.0/) quite long ago (December 2, 2019 - **half year ago** at the moment of writing). The support of Django 3.0 has long been needed. Is django-polymorphic going to support it?

If yes, then at least the following must be done:
1. Update [the test configuration](https://github.com/django-polymorphic/django-polymorphic/blob/37403c7421f08c96634f46d970acde969a60f454/.travis.yml#L11-L39) to run tests with Django 3.0. See PR #425.
2. Fix #424. (This bug is about `RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy()`.)
3. Fix #432. (This bug is about `ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models'`.)
4. ... (Are there any other know bugs related to Django 3.0? List them here, please.)
5. Update [README.rst](https://github.com/django-polymorphic/django-polymorphic/blob/37403c7421f08c96634f46d970acde969a60f454/README.rst#features). Now it states that:

	> The current release of django-polymorphic supports Django 1.11, 2.0, 2.1, 2.2

6. Update [the documentation](https://django-polymorphic.readthedocs.io/en/stable/quickstart.html#quickstart). Now it states that:

	> The current release of django-polymorphic supports Django 1.11, 2.0 

7. Update [the metadata](https://github.com/django-polymorphic/django-polymorphic/blob/37403c7421f08c96634f46d970acde969a60f454/setup.cfg#L16-L20) of the [`django-polymorphic`](https://pypi.org/project/django-polymorphic/) project on PyPi. Now it states the following:

	> Framework
	> * Django
	> * Django :: 1.11
	> * Django :: 2.0
	> * Django :: 2.1
	> * Django :: 2.2

**Comment by morrme** [comment]
Is this work that will be added to #425 or are you seeking a separate contribution for this?

**Comment by Ouradze** [comment]
Hi, Any news on this ? Django just dropped the compatibility for `ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models'` in 3.1.

**Comment by OmenApps** [comment]
Yep, should import from django.core.exceptions, where FieldDoesNotExist is actually defined. Just put in a PR #451, but there doesn't seem to be much activity here, so I'm resorting to using my own forked copy for now :(

**Comment by thanosd** [comment]
Happy to help with anything here to get this over the line.

**Comment by chrisglass** [comment]
Some support for django 3.x landed in master today. Yes, the maintenance of this package is severly lacking in terms of manpower... volunteers welcome.

One of the things I'd like to see (as a not=involved-with-django-anymore programmer) are passing tox tests for django3.* in master. This is not currently the case, and something you can help with.

**Comment by chrisglass** [comment]
For the record, I think points 5. 6. and 7. in your list should be fixed.

**Comment by yakky** [comment]
@chrisglass @AndreyMZ #

1, 3, 4, 5, 6, 7 landed on master with #452 
2. Fixed by #457
