### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by AndreyMZ** [django-polymorphic/django-polymorphic#444]
Python 3.8 was [released](https://www.python.org/downloads/release/python-380/) quite long ago (October 14, 2019 - **8 months ago** at the moment of writing). The support of Python 3.8 has long been needed. Is django-polymorphic going to support it?

If yes, then at least the following must be done:
1. Update [the test configuration](https://github.com/django-polymorphic/django-polymorphic/blob/37403c7421f08c96634f46d970acde969a60f454/.travis.yml#L11-L39) to run tests with Python 3.8. See PR #425.
2. Update [the metadata](https://github.com/django-polymorphic/django-polymorphic/blob/37403c7421f08c96634f46d970acde969a60f454/setup.cfg#L24-L28) of the [`django-polymorphic`](https://pypi.org/project/django-polymorphic/) project on PyPi. Now it states the following:

	> Programming Language
	> * Python :: 2.7
	> * Python :: 3
	> * Python :: 3.5
	> * Python :: 3.6
	> * Python :: 3.7

	The following is expected:
	
	> Programming Language
	> * Python :: 2
	> * Python :: 2.7
	> * Python :: 3
	> * Python :: 3.5
	> * Python :: 3.6
	> * Python :: 3.7
	> * Python :: 3.8

**Comment by chrisglass** [comment]
This was fixed in master with #452 (I think).

Please repoen a bug should it not be actually fixed.
