### ISSUE TITLE
PyPI sdist lacks tests

### ISSUE THREAD

**Issue by jayvdb** [django-polymorphic/django-polymorphic#463]
The sdist only contains a few tests files, missing the actual tests

```
...
./django-polymorphic-3.0.0/polymorphic/templatetags/polymorphic_formset_tags.py
./django-polymorphic-3.0.0/polymorphic/tests
./django-polymorphic-3.0.0/polymorphic/tests/migrations
./django-polymorphic-3.0.0/polymorphic/tests/migrations/0001_initial.py
./django-polymorphic-3.0.0/polymorphic/tests/migrations/__init__.py
./django-polymorphic-3.0.0/polymorphic/utils.py
...
```

**Comment by vdboor** [comment]
the tests are explicitly excluded. I've extended this rule to avoid cluttering the install

**Comment by jayvdb** [comment]
Normal users install the wheel, which is not the sdist and wont include these tests.  The sdist is able to be used by distros who can set up a proper test rig. e.g. https://repology.org/project/python:django-polymorphic/versions . fwiw I am one of those package maintainers.  Anyway, thanks for working through the backlog.
