### ISSUE TITLE
Polymorphic and multi database router

### ISSUE THREAD

**Issue by kapt** [django-polymorphic/django-polymorphic#55]
I encounter a problem when using django-polymorphic with the built-in django database router: 

the method `get_real_instance_class` of `PolymorphicModel` retreives a ContentType without defining the database to use (`ContentType.objects.get_for_id(...)`).

Does polymorphic support multi database?

**Comment by hobarrera** [comment]
There's currently tests that run on multiple databases, and check the class of the returned instances. Looks like this is closable.
