### ISSUE TITLE
Placing non polymorphic model after a polymorphic model can cause AttributeError no base_objects

### ISSUE THREAD

**Issue by stuaxo** [django-polymorphic/django-polymorphic#9]
Sometimes I'll get an error like this:

AttributeError  type object XXX has no attribute 'base_objects'

The class XXXX is always one that inherits from models.Model, and generally later in my models file than a polymorphic class.   Reordering the class file to put the normal models further up fixes it.

Here's an example trace, with 'Region' which extends model.Model causing the error:
https://gist.github.com/2966844

Model of Region:

``` python
class Region(models.Model):
    name = CharField(max_length=256)

    def __unicode__(self):
        return self.name
```

**Comment by pabdelhay** [comment]
The problem is indeed when you **put a non-polymorphic model as parent of a polymorphic model**. I had this problem when I tried to remove child objects.

My models:
```
class Resource(models.Model):
    ...
class Service(PolymorphicModel, Resource):
    ...
class ServiceA(Service):
    ...
```

The solution was to put the base_objects manager in the top parent model. So, my Resource model now has the base_objects and everything works fine:
```
class Resource(models.Model):
    ...
    objects = models.Manager()
    base_objects = models.Manager()
```

Hope it helps! ;)

**Comment by stuaxo** [comment]
It's years since I was using this ... BUT this is very useful info, as a gotchya it should be in the docs, or better there should be an error raised explaining this (or even better it would just-work).

**Comment by vdboor** [comment]
Ah, I see. I'm reopening this for someone to look into. I won't do this due to time contraints

**Comment by guardd0gg** [comment]
The solution above doesn't work for me, for some reason.  I've got:

`
class Stimulus(PolymorphicModel):
    stimulus_id = models.AutoField(primary_key = True) #prevent name clashes in multiple-inheritance scenarios

    class Meta:
        verbose_name_plural = "Stimuli"

class Vitals(models.Model):
    vitals_id = models.AutoField(primary_key = True) #prevent name clashes in multiple-inheritance scenarios
    ...
class Human(Stimulus, Vitals):
    ...
class Animal(Stimulus, Vitals):
    ...
`
While I don't get the AttributeError after trying the above solution, I now get a `Vitals.DoesNotExist` exception when trying to delete any of `Human/Animal/Vitals/Stimulus`.  `base_objects` is being passed in the `pk` for `Stimulus` every time, which is incorrect and causes the object not to be found (thankfully, there are more `Stimulus` rows in the database than there are `Vitals`, or I would not have caught this as easily).

What's the solution here?  I can post more code/specific error output, if needed.

**Comment by cdruck** [comment]
Got the same error and spent the morning on this. I am giving up on polymorphic until this is resolved.

**Comment by foarsitter** [comment]
My solution is to add _base_objects to auth.Group on runtime when the PolymorphicModel is created. 
```
setattr(Group, '_base_objects', Group.objects)

class Actor(PolymorphicModel, Group):
```

Is it a solution to add a check `hasattr("_base_objects")` in [polymorphic/models.py:208 ](https://github.com/django-polymorphic/django-polymorphic/blob/master/polymorphic/models.py#L208) adn return objects when False?

**Comment by stuaxo** [comment]
I think the best thing, is to try it, then make some unit tests that create Models that fail with the old code and work with the new code.

Reading the comments in that code, it sounds about right, but its 8 years since I reported this, I'm not as close to it as you are :)

**Comment by foarsitter** [comment]
Sound like a fun thing tot try, I will give it a shot!

**Comment by stuaxo** [comment]
Ace :)   this ticket seems a great place to start for examples that fail.
